language: python
python:
  - 2.7
  - 3.6

install:
  - pip install codecov

script:
  - export RENTABOT_RESOURCE_DESCRIPTOR="tests/assets/resource_descriptor.yaml"
  - python setup.py test

after_success:
  - codecov
